env:
    CIRRUS_CLONE_DEPTH: 1
    BUILD_HOSTNAME: "b"
task:
 name: SSH
 container:
    image: apon77/aosp:cirrus
cpu: 2
memory: 4
ssh_script:

- sudo apt-get update
- sudo apt-get install tmate
- ssh-keygen
- tmate

