env:
    CIRRUS_CLONE_DEPTH: 1
    BUILD_HOSTNAME: "b"

  
task:
  persistent_worker:
    labels:
      name: AX61-2
    isolation:
      container:
        image: apon77/aosp:cirrus
        cpu: 64
        memory: 128 
- sudo apt-get update
- sudo apt-get install tmate
- ssh-keygen
- tmate

Footer
