env:
    CIRRUS_CLONE_DEPTH: 1
    BUILD_HOSTNAME: "b"

  

task:
  name: Build
  timeout_in: 4h
      container:
        image: ubuntu
        cpu: 24
        memory: 120G
        volumes:
          - /home/cirrus/roms:/home/cirrus/roms
          - /home/cirrus/ccache:/home/cirrus/ccache
          - /home/cirrus/.config:/home/cirrus/.config 
